services:
  # üöÄ Aplicaci√≥n .NET
  web:
    build: .
    container_name: ZenCloud
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://*:8080"

      # üîê Configuraci√≥n principal
      CONNECTION_STRING: "${CONNECTION_STRING}"
      SMTP_SERVER: "${SMTP_SERVER}"
      SMTP_PORT: "${SMTP_PORT}"
      SMTP_USERNAME: "${SMTP_USERNAME}"
      SMTP_PASSWORD: "${SMTP_PASSWORD}"
      SMTP_FROMEMAIL: "${SMTP_FROMEMAIL}"
      SMTP_FROMNAME: "${SMTP_FROMNAME}"

      # üîó Connection Strings COMPLETAS desde variables
      ConnectionStrings__MySQL: "Server=${MYSQL_HOST};Port=${MYSQL_PORT};Database=${MYSQL_DEFAULT_DATABASE};User=${MYSQL_ADMIN_USER};Password=${MYSQL_ADMIN_PASSWORD};"
      ConnectionStrings__Postgres: "Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_DEFAULT_DATABASE};Username=${POSTGRES_ADMIN_USER};Password=${POSTGRES_ADMIN_PASSWORD};"
      ConnectionStrings__Mongo: "mongodb://${MONGO_ADMIN_USER}:${MONGO_ADMIN_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DEFAULT_DATABASE}"
      ConnectionStrings__Redis: "${REDIS_HOST}:${REDIS_PORT},password=${REDIS_ADMIN_PASSWORD}"

    depends_on:
      - mysql-ZenDb
      - postgres-ZenDb
      - sqlserver-ZenDb
      - mongo-ZenDb
      - cassandra-ZenDb
      - redis-ZenDb

  # üê¨ MySQL
  mysql-ZenDb:
    image: mysql:8.0
    container_name: mysql-ZenDb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ADMIN_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DEFAULT_DATABASE}"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ADMIN_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # üêò PostgreSQL
  postgres-ZenDb:
    image: postgres:16
    container_name: postgres-ZenDb
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_ADMIN_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_ADMIN_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DEFAULT_DATABASE}"
    ports:
      - "5433:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data
    
  # üçÉ MongoDB
  mongo-ZenDb:
    image: mongo:8
    container_name: mongo-ZenDb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_ADMIN_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_ADMIN_PASSWORD}"
      MONGO_INITDB_DATABASE: "${MONGO_DEFAULT_DATABASE}"
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  
  # ‚ö°  Redis
  redis-ZenDb:
    image: redis:7
    container_name: redis-ZenDb
    restart: always
    command: [ "redis-server", "--requirepass", "${REDIS_ADMIN_PASSWORD}" ]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  postgres_data:
  mongo_data:
  redis_data:
